# Generated by Django 4.1.3 on 2022-12-09 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_apply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='end_data',
            new_name='end_date',
        ),
    ]
