# Generated by Django 4.1.3 on 2022-12-10 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_rename_end_data_job_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='resume',
        ),
        migrations.AddField(
            model_name='apply',
            name='proficiency',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
