# Generated by Django 4.1.3 on 2022-12-10 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_remove_apply_resume_apply_proficiency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='proficiency',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
